nelmio_cors:
  defaults:
    allow_credentials: false
    allow_origin: ["*"]
    allow_headers: ["Content-Type", "Authorization"]
    expose_headers: ["Link"]
    allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
    max_age: 3600
  paths:
    "^/api/":
      allow_origin: ["*"]
      allow_headers: ["Content-Type", "Authorization"]
      allow_methods: ["GET", "OPTIONS", "POST", "PUT", "DELETE"]
      max_age: 3600
# defaults:
#   origin_regex: true
#   allow_origin: ["%env(CORS_ALLOW_ORIGIN)%"]
#   allow_methods: ["GET", "OPTIONS", "POST", "PUT", "PATCH", "DELETE"]
#   allow_headers: ["Content-Type", "Authorization"]
#   expose_headers: ["Link"]
#   max_age: 3600
# paths:
#   "^/": null
