controllers:
  resource:
    path: ../src/Controller/
    namespace: App\Controller
  type: attribute

app_checkout:
  path: /stripe/checkout/{id}
  controller: App\Controller\StripeController::stripeCheckout
  methods: [POST, GET]

app_product_details:
  path: "/details/{id}"
  controller: 'App\Controller\ProductController::showDetails'

app_facture:
  path: /Facture_mail/{orderId}
  controller: App\Controller\OrderController::envoyerFacture
  methods: [POST]

api_login_check:
  path: /api/login_check
  methods: ["POST"]

app_accueil:
  path: /
  controller: App\Controller\AccueilController::index
# # config/routes.yaml
# app_order_details:
#   path: /order-details/{id}
#   controller: App\Controller\OrderDetailsController::showOrder
